const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "NAME", uid: "petName", sortable: true },
  { name: "SPECIES", uid: "species", sortable: true },
  { name: "GENDER", uid: "gender", sortable: true },
  { name: "BREED", uid: "breed", sortable: true },
  { name: "AGE", uid: "age", sortable: true },
  { name: "WEIGHT", uid: "weight", sortable: true },
  { name: "OWNER", uid: "ownerName", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

const users = [
  {
    id: 1,
    petName: "Negi",
    species: "Dog",
    gender: "Male",
    breed: "Labrador Retriever",
    age: "3",
    weight: "10.5",
    ownerName: "Jhayson Quirao",
    status: "active",
    avatar: "",
  },
  {
    id: 2,
    petName: "Bella",
    species: "Cat",
    gender: "Female",
    breed: "Siamese",
    age: "2",
    weight: "4.2",
    ownerName: "Alice Smith",
    status: "paused",
    avatar: "",
  },
  {
    id: 3,
    petName: "Max",
    species: "Dog",
    gender: "Male",
    breed: "German Shepherd",
    age: "5",
    weight: "30.0",
    ownerName: "Bob Johnson",
    status: "vacation",
    avatar: "",
  },
  {
    id: 4,
    petName: "Luna",
    species: "Cat",
    gender: "Female",
    breed: "Maine Coon",
    age: "1",
    weight: "5.0",
    ownerName: "Jhayson Quirao",
    status: "active",
    avatar: "",
  },
  {
    id: 5,
    petName: "Charlie",
    species: "Dog",
    gender: "Male",
    breed: "Beagle",
    age: "4",
    weight: "12.0",
    ownerName: "Alice Smith",
    status: "paused",
    avatar: "",
  },
  {
    id: 6,
    petName: "Lucy",
    species: "Cat",
    gender: "Female",
    breed: "Persian",
    age: "3",
    weight: "4.5",
    ownerName: "Bob Johnson",
    status: "vacation",
    avatar: "",
  },
  {
    id: 7,
    petName: "Buddy",
    species: "Dog",
    gender: "Male",
    breed: "Golden Retriever",
    age: "2",
    weight: "25.0",
    ownerName: "Kween Leng",
    status: "active",
    avatar: "",
  },
  {
    id: 8,
    petName: "Milo",
    species: "Cat",
    gender: "Male",
    breed: "Bengal",
    age: "1",
    weight: "3.5",
    ownerName: "John Doe",
    status: "paused",
    avatar: "",
  },
  {
    id: 9,
    petName: "Rocky",
    species: "Dog",
    gender: "Male",
    breed: "Bulldog",
    age: "4",
    weight: "20.0",
    ownerName: "Jane Smith",
    status: "vacation",
    avatar: "",
  },
  {
    id: 10,
    petName: "Zoe",
    species: "Cat",
    gender: "Female",
    breed: "Ragdoll",
    age: "3",
    weight: "4.0",
    ownerName: "Alice Johnson",
    status: "active",
    avatar: "",
  },
  {
    id: 11,
    petName: "Daisy",
    species: "Dog",
    gender: "Female",
    breed: "Poodle",
    age: "5",
    weight: "8.0",
    ownerName: "Bob Brown",
    status: "paused",
    avatar: "",
  },
  {
    id: 12,
    petName: "Loki",
    species: "Cat",
    gender: "Male",
    breed: "Sphynx",
    age: "2",
    weight: "3.0",
    ownerName: "Charlie Davis",
    status: "vacation",
    avatar: "",
  },
  {
    id: 13,
    petName: "Coco",
    species: "Dog",
    gender: "Female",
    breed: "Chihuahua",
    age: "3",
    weight: "2.5",
    ownerName: "Diana Evans",
    status: "active",
    avatar: "",
  },
  {
    id: 14,
    petName: "Simba",
    species: "Cat",
    gender: "Male",
    breed: "Savannah",
    age: "4",
    weight: "5.0",
    ownerName: "Ethan Foster",
    status: "paused",
    avatar: "",
  },
  {
    id: 15,
    petName: "Buster",
    species: "Dog",
    gender: "Male",
    breed: "Boxer",
    age: "6",
    weight: "28.0",
    ownerName: "Fiona Green",
    status: "vacation",
    avatar: "",
  },
  {
    id: 16,
    petName: "Misty",
    species: "Cat",
    gender: "Female",
    breed: "Russian Blue",
    age: "2",
    weight: "3.8",
    ownerName: "George Harris",
    status: "active",
    avatar: "",
  },
];

export { columns, users, statusOptions };
