const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "NAME", uid: "name", sortable: true },
  { name: "AGE", uid: "age", sortable: true },
  { name: "ROLE", uid: "role", sortable: true },
  // { name: "TEAM", uid: "team" },
  { name: "EMAIL", uid: "email" },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

const users = [
  {
    id: 1,
    name: "Jhayson Quirao",
    role: "Admin",
    team: "",
    status: "active",
    age: "23",
    avatar: "",
    email: "jcquirao@ccc.edu.ph",
  },
  {
    id: 2,
    name: "Kween Yasmin",
    role: "Veterinary",
    team: "",
    status: "active",
    age: "30",
    avatar: "",
    email: "kween.yasmin@gmail.com",
  },
  {
    id: 3,
    name: "Bianca Eaton",
    role: "Veterinary Receptionist",
    team: "",
    status: "active",
    age: "26",
    avatar: "",
    email: "et.ultrices@aol.edu",
  },
  {
    id: 4,
    name: "Olga Woodward",
    role: "Veterinary Nurse",
    team: "",
    status: "active",
    age: "25",
    avatar: "",
    email: "lorem.sit@google.org",
  },
  {
    id: 5,
    name: "John Doe",
    role: "Veterinary Assistant",
    team: "",
    status: "paused",
    age: "28",
    avatar: "",
    email: "john.doe@example.com",
  },
  {
    id: 6,
    name: "Jane Smith",
    role: "Veterinary Technician",
    team: "",
    status: "vacation",
    age: "32",
    avatar: "",
    email: "jane.smith@example.com",
  },
  {
    id: 7,
    name: "Emily Johnson",
    role: "Veterinary Surgeon",
    team: "",
    status: "active",
    age: "29",
    avatar: "",
    email: "emily.johnson@example.com",
  },
  {
    id: 8,
    name: "Michael Brown",
    role: "Veterinary Pathologist",
    team: "",
    status: "active",
    age: "34",
    avatar: "",
    email: "michael.brown@example.com",
  },
  {
    id: 9,
    name: "Jessica Davis",
    role: "Veterinary Radiologist",
    team: "",
    status: "paused",
    age: "27",
    avatar: "",
    email: "jessica.davis@example.com",
  },
  {
    id: 10,
    name: "David Wilson",
    role: "Veterinary Anesthesiologist",
    team: "",
    status: "active",
    age: "31",
    avatar: "",
    email: "david.wilson@example.com",
  },
  {
    id: 11,
    name: "Sarah Martinez",
    role: "Veterinary Nutritionist",
    team: "",
    status: "vacation",
    age: "33",
    avatar: "",
    email: "sarah.martinez@example.com",
  },
  {
    id: 12,
    name: "James Anderson",
    role: "Veterinary Behaviorist",
    team: "",
    status: "active",
    age: "35",
    avatar: "",
    email: "james.anderson@example.com",
  },
  {
    id: 13,
    name: "Patricia Thomas",
    role: "Veterinary Epidemiologist",
    team: "",
    status: "paused",
    age: "30",
    avatar: "",
    email: "patricia.thomas@example.com",
  },
  {
    id: 14,
    name: "Robert Jackson",
    role: "Veterinary Microbiologist",
    team: "",
    status: "active",
    age: "28",
    avatar: "",
    email: "robert.jackson@example.com",
  },
];

export { columns, users, statusOptions };
